x = (input("Enter the first number :"))
y = (input("Enter the second number :"))
print("Concatinating two number:", x+y)
print("Addition of two number is:",int(x)+int(y))
print("Subtraction of two number is:",int(x)-int(y))
print("Multiplication of two number is:",int(x)*int(y))
print("Division of two number is:",int(x)/int(y))
